### ISSUE TITLE
Configure cache profile settings

### ISSUE THREAD

**Issue by dubahu** [MicrosoftDocs/OfficeDocs-SharePoint#1067]
Not working as documented.  After making the changes in web.config, the site collection settings are still taking precedence.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 368e4065-54b4-6973-3fb3-c33d3d5e905a
* Version Independent ID: a85911df-492d-855f-82a6-c1725952945b
* Content: [Configure cache settings for a web application in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/cache-settings-configuration-for-a-web-application#feedback)
* Content Source: [SharePoint/SharePointServer/administration/cache-settings-configuration-for-a-web-application.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/cache-settings-configuration-for-a-web-application.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by tseward** [comment]
What value are you setting the maxSize to and what is the actual value you're seeing?

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by dubahu** [comment]
> What value are you setting the maxSize to and what is the actual value you're seeing?

I was setting cache profile rather than object cache, so no value for maxSize.  This is the what I set:
<OutputCacheProfiles useCacheProfileOverrides="true" varyByHeader="" varyByParam="*" varyByCustom="" varyByRights="true" cacheForEditRights="false" />

Even after that, only the values I set in the site collection are applied.  Nothing changes until I change them there.

**Comment by tseward** [comment]
@dubahu I'll take a look at this next week and follow up.

**Comment by tseward** [comment]
@dubahu so the only thing you're setting there is the varyByRights to true with no other cache profile override settings. What are you expecting to see when you set this value, or where you expecting to see something on the Publishing Site Output Cache Settings page?

**Comment by dubahu** [comment]
I've actually tried no other settings, setting other options, such as lifetime, but nothing changes.  What I'm expecting is what the article states: "If page output cache profiles are enabled at the web application level, the settings specified in Web.config will be used for all page output cache profiles, overriding any values that have been entered through the user interface at the site collection level."

That is not happening, no matter what I set in the web.config, it doesn't apply.  Even with the setting still in the web.config, if I make changes at the site collect level, they are still applied independently by site collection.  The only difference I could see with these site collection that isn't specifically mentioned in this article is that they are host named site collections.

**Comment by tseward** [comment]
OK, so in my testing here's what I saw:

1) The Output Cache in /_layouts/15/sitecachesettings.aspx must be enabled, even if `useCacheProfileOverrides` is set to `true`. if `useCacheProfileOverrides` is set to `true` but the Output Cache is not enabled, caching profiles will not be used.

2) When Output Cache is enabled and `useCacheProfileOverrides` is set to true, the UI notes that the admin has overridden specific settings within each cache profile selected. You're still able to select any cache profile and edit all cache profile settings, but specific settings in each cache profile will be overridden by what has been placed in the web.config.

I can see when `useCacheProfileOverrides` is set to true and my cache profile (Intranet, in this case) is set to a Duration of 10, the page shows `Cache-Control: public` and I see the expected 10 second expiration. This, to me, shows that it is working correctly.

Note I'm testing with SharePoint Server 2016 with a mid-2019 PU.

**Comment by scanum** [comment]
@dubahu Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by dubahu** [comment]
It isn't resolved.  I'm using SharePoint 2013, current CU.  These are cache profiles set on anonymous sites, so it is definitely read only.

**Comment by dubahu** [comment]
> @dubahu Thank you for submitting feedback. We understand that this issue has been resolved.
> Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

It isn't resolved. I'm using SharePoint 2013, current CU. These are cache profiles set on anonymous sites, so it is definitely read only.

**Comment by dubahu** [comment]
@officedocsbot open

**Comment by dubahu** [comment]
@scanum How do I reopen this?

**Comment by tseward** [comment]
@dubahu what we need to know is if this is a bug, then this repo isn't the correct way to report it. I'd suggest you open a case with Microsoft (support.microsoft.com). If it is a bug, it likely needs to be fixed. If they determine it is working as intended, then documentation needs to be updated.
