### ISSUE TITLE
Set-SPOTenant -SyncAadB2BManagementPolicy $True

### ISSUE THREAD

**Issue by brassman2000** [MicrosoftDocs/OfficeDocs-SharePoint#1133]
Our Office365 Tenant used for testing has the AAD B2B private preview and we are looking to enable integration with SharePoint/OneDrive.

After calling Set-SPOTenant -SyncAadB2BManagementPolicy $True, a subsequent call to validate the change via Get-SPOTenant shows that SyncAadB2BManagementPolicy is still $False.

Is this an issue with the API or our Tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [SharePoint and OneDrive integration with Azure AD B2B (Preview)](https://docs.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration-preview#feedback)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MSFTRafLop** [comment]
Hi @brassman2000 sorry about this confusing behavior. When you run Set-SPOTenant -SyncAadB2BManagementPolicy $true it does tell SPO to sync AAD policies/settings. The reason the Get-SPOTenant command still returns $false is because "SyncAadB2BManagementPolicy" is not something which carries state. We'll make a change to just remove SyncAadB2BManagementPolicy from Get-SPOTenant.

In the meantime, just know that if you ran Set-SPOTenant -SyncAadB2BManagementPolicy $true then SPO did sync down AAD policies/settings (such as the opt-in status for OTP preview). This happens automatically on a set time interval, but when you run the command it forces a sync to happen immediately.

Does -EnableAzureADB2BIntegration $true work for you? If you get a message about it not being supported in your version of the service, it's because the preview is still in the process of rolling out to everyone. We expect the rollout to complete within the next ten days.

**Comment by brassman2000** [comment]
Thanks for the update.  Yes - setting -EnableAzureADB2BIntegration to $true works as expected and the new state is reflected in a subsequent call to Get-SPOTenant.

**Comment by scanum** [comment]
@brassman2000 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by abates100** [comment]
I am still having issues with these settings -SyncAadB2BManagemenPolicy remains false and  the other is MIA.  A parameter cannot be found that matches parameter name 'EnableAzureADB2BIntegration'  Is the rollout still not complete?

**Comment by abates100** [comment]
I am still having issues with these settings -SyncAadB2BManagemenPolicy remains false and  the other is MIA.  A parameter cannot be found that matches parameter name 'EnableAzureADB2BIntegration'  Is the rollout still not complete?

**Comment by abates100** [comment]
This documentation is very confusing.  https://docs.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration-preview#feedback  and https://docs.microsoft.com/en-us/azure/active-directory/b2b/one-time-passcode#opting-in-to-the-preview

**Comment by MikePlumleyMSFT** [comment]
@abates100, the most likely cause of missing parameters is not having the required PowerShell module version or having multiple versions installed (see issue #1260).

**Comment by abates100** [comment]
That was fun, not. I did have multiple versions, an older Online Shell  as well as a PNP module.  Uninstalled all the module versions, didn't work. Then uninstalled the shell, then reinstalled just the the module 9119.1200  and Connect-SPOService was MIA!  Had to uninstall the module and reinstall the shell before I finally had the  -EnableAzureADB2BIntegration property.  Also now I see the SyncAadB2bManagementPolicy is no longer listed in Get-SPOTenant.  Thanks for the quick help!
