### ISSUE TITLE
Sharepoint Library ID

### ISSUE THREAD

**Issue by woodyard** [MicrosoftDocs/OfficeDocs-SharePoint#1326]
The "Copy Library ID" button/link on the "Get ready to sync"-page is gone. Please advise how to obtain the Library ID now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy#feedback)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by win2000b** [comment]
This seeems to be very hit and miss. Sometimes the option is there on some tenants and others its not. As you can see from the screenshot. No option to copy the ID.

![image](https://user-images.githubusercontent.com/22396470/64706624-b69fd380-d4a9-11e9-8c34-51a1a024fd35.png)

**Comment by r0bu** [comment]
It also appears to be inconsistent on the same tenant, sometimes providing the ID and other times not (see above).

**Comment by tseward** [comment]
Looks like the dialog is from the classic interface, rather than what @win2000b pictured above, which is the modern interface. Let me discuss altering the article, but this is the easiest way in my personal opinion. Get the [SharePoint PnP cmdlets](https://www.powershellgallery.com/packages/SharePointPnPPowerShellOnline).

```powershell
Connect-PnPOnline https://tenantName.sharepoint.com/sites/siteName
Get-PnPSite -Includes Id | Select Id
Get-PnPWeb | Select Id
Get-PnPList 'Documents' | Select Id
```

This will give you all three components you need for the GPO to auto-sync a library.

**Comment by AJRus** [comment]
Hey tseward - when i run that cmdlet, i get the following error;

Connect-PnPOnline : The sign-in name or password does not match one in the Microsoft account system.
At line:1 char:1

My account is a business/education account.. not a Microsoft.

**Comment by AJRus** [comment]
I was able to connect using connect-sposervice - but it's not obviously what the equivalent of those commands would be..

**Comment by scanum** [comment]
@woodyard Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by r0bu** [comment]
I’m sorry to say I just checked one of my tenants and it’s definitely not fixed

**Comment by Revolu** [comment]
> 
> 
> @AJRus if you do not have MFA or modern auth enabled, drop the `-SPOManagementShell` switch. @win2000b design change for a modern interface.

Very bad decision to remove this but ok... thanks I guess

**Comment by kenwith** [comment]
Re-opening as @tseward has a PR to help address. We can close once that is resolved.

**Comment by DKhalaf** [comment]
Jesus I just want to automatically sync sharepoint libraries to users!! WHy is this so difficult!????

**Comment by scanum** [comment]
@tseward Any update on this issue? Thanks!

**Comment by tseward** [comment]
@scanum this can be closed. It was addressed elsewhere.

**Comment by AJRus** [comment]
Where was this addressed? It's still missing.

**Comment by AJRus** [comment]
Just a note - you have to be logged in as a sharepoint or global admin to get the Library ID - the documentation does reflect that. I dont believe I missed that in my initial review.

**Comment by tseward** [comment]
Any user with access to the library can get the ID.

**Comment by AJRus** [comment]
According to the program manager, the Copy Library ID is only available to a tenant admin, and the documentation now reflects that you have to be a Sharepoint or Global admin to obtain it.

**Comment by tseward** [comment]
No, that isn't true at all. The library ID is exposed to anyone who can view the library settings (it's part of the URL) and there are other means to get the ID that non-admins can use, e.g. PnP cmdlets.

**Comment by scanum** [comment]
@woodyard Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by djpirocchi** [comment]
How was this resolved?  

I am not getting the copy library id link with my Global Administrator account.  I've had mixed success with a PowerShell script connecting to the PnPCmdlets.  For some sites the cmdlets do not have access.  I am using the trick to get it to communicate via TLS1.2 and we have Modern Auth enabled, so I am using the -SPOManagementShell switch.

I even have Microsoft Case #: 19599818 actively open at this point.

**Comment by greenstarthree** [comment]
I would second that this is not resolved. 

When logged in as a Global Tenant Admin, I do not get the Copy Library ID link in either Firefox, Edge (Chromium) or Internet Explorer.

3 weeks ago I was able to do this while logged in as a Tenant Admin user - what's changed?

**Comment by weyCC81** [comment]
* Logged-In as a User 
"Copy library ID" is **not available** on Sync-Button from CommunicationSite

* Logged-In as s Global Admin
"Copy library ID" is **available** on Sync-Button from CommunicationSite

**Comment by chiners68** [comment]
I dont even get the modern looking box let alone the library ID. This is logged in as global admin

![image](https://user-images.githubusercontent.com/41296237/120670593-7b68e380-c488-11eb-966a-751d6483cf3b.png)

**Comment by KillZwitch** [comment]
If I get an E5 license, can I get the copy ID link back?

**Comment by tech1982** [comment]
This is not resolved

**Comment by scanum** [comment]
@gacarini Hope all is well. I sthis something you can help with? Thanks!

**Comment by dariomws** [comment]
@tseward, could you confirm your last statement? Thanks!

**Comment by HansBrender** [comment]
the Issue is fixed .

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
