### ISSUE TITLE
[LOC] Invalid link in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-SharePoint#1654]
There is an invalid link in an article:

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/OneDrive/pre-provision-accounts
2. Search for the "OneDrive for Business Service Description" Link
3. Click on the link

**Actual results:**
Link does not work
**Expected result:**
Link should work

**GH article:**
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/pre-provision-accounts.md

![image](https://user-images.githubusercontent.com/47977325/71899117-5c630680-315b-11ea-8b19-34e433f6d67d.png)

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by OfficeGlobal** [comment]
Hello,

The issue is still repro, could you please check it again ?

Thank you

**Comment by lindspea** [comment]
@OfficeGlobal I'll have a look now and let you know soonest.

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
