### ISSUE TITLE
Inaccurate info - Needs update

### ISSUE THREAD

**Issue by andocromn** [MicrosoftDocs/OfficeDocs-SharePoint#1795]
under the section "Configure team site libraries to sync automatically" it describes "Copy library ID" which no longer exists in Office 365 platform
please update with accurate info

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy#feedback)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@andocromn Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jeopardize95** [comment]
Any update on this? Critical function, and it's gone. How do I generate the ID?

**Comment by andocromn** [comment]
@jeopardize95 I ended up using the incredibly awkward and backassward method described in this article 
https://www.blackforce.co.uk/2019/09/12/sharepoint-copy-library-id-missing-for-team-site-libraries-sync
I was like NFW this is going to work! but it actually did.  Microsoft certainly needs to fix this though cause it's a workaround like removing and re-attaching a foot is a solution to foot pain

**Comment by jeopardize95** [comment]
@andocromn I've tried. But then Intune won't sync the library. Have a case with MS on it, but doesn't seem to lead anywhere. This is ridiculous, this function is noted in Docs, but not working. Works in one tenant I have, but not the other. Hopeless.

**Comment by andocromn** [comment]
@jeopardize95 sorry to hear that.  For what it's worth it does seem to be hit or miss, I just had to manually add it for a user myself.  Maybe I could have banged away at OneDrive and gotten it to work but the doc says something about 8 hours and even a saint doesn't have that kind of patience.  Best of luck

**Comment by dariomws** [comment]
Hi @andocromn and @jeopardize95, thank you for your feedback.

I tested in two different tenants and it works for me:
![image](https://user-images.githubusercontent.com/33589238/76902611-2b016800-687b-11ea-9b87-2cbc6092b51a.png)
I encourage you to continue working with support as this is the correct way to handle this problem.

Docs feedback is available to improve documentation and it seems to be an issue in your tenant.

Thanks again!

**Comment by jeopardize95** [comment]
Hello Dario,
That’s strange. Would you like me to show you? Happens in three of my tenants :-(

Med vennlig hilsen
Andreas Aasheim
Arkitekt | Microsoft 365
Tlf: 98114408
Easify AS
________________________________
Fra: Dario Woitasen <notifications@github.com>
Sendt: Tuesday, March 17, 2020 10:16:49 PM
Til: MicrosoftDocs/OfficeDocs-SharePoint <OfficeDocs-SharePoint@noreply.github.com>
Kopi: Andreas Aasheim <andreas@easify.no>; Mention <mention@noreply.github.com>
Emne: Re: [MicrosoftDocs/OfficeDocs-SharePoint] Inaccurate info - Needs update (#1795)


Hi @andocromn<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fandocromn&data=02%7C01%7Candreas%40easify.no%7Cccab841edcee468bcd1608d7cab882b9%7C0c8060178696416998d7b89a4499da8a%7C0%7C0%7C637200766137106194&sdata=UvswH9Ymh3fPGexbQU%2BZzJL62iIhAVeulYU5D5IFJc8%3D&reserved=0> and @jeopardize95<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjeopardize95&data=02%7C01%7Candreas%40easify.no%7Cccab841edcee468bcd1608d7cab882b9%7C0c8060178696416998d7b89a4499da8a%7C0%7C0%7C637200766137106194&sdata=mNPCCwENhMwV65xCdRvbyLrCFlrvfV4qnxbEKV%2FHu40%3D&reserved=0>, thank you for your feedback.

I tested in two different tenants and it works for me:
[image]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F33589238%2F76902611-2b016800-687b-11ea-9b87-2cbc6092b51a.png&data=02%7C01%7Candreas%40easify.no%7Cccab841edcee468bcd1608d7cab882b9%7C0c8060178696416998d7b89a4499da8a%7C0%7C0%7C637200766137116187&sdata=F0Z5Muo355Zrw0c8ILvQLJ4akn5ZNfbLcSC8hm42TgU%3D&reserved=0>
I encourage you to continue working with support as this is the correct way to handle this problem.

Docs feedback is available to improve documentation and it seems to be an issue in your tenant.

Thanks again!

**Comment by dariomws** [comment]
Sorry, I think you should continue working with support as I cannot provide you with this kind of assistance.

**Comment by andocromn** [comment]
Hi @dariomws

**Comment by andocromn** [comment]
Hi @dariomws, can you please provide further detail?  I have followed the instructions, Please see the screenshot showing that the Copy Library Link is not available.  thank you

![2020-03-17 18_04_51-Microsoft Edge](https://user-images.githubusercontent.com/1273420/76906520-7c5d2780-687a-11ea-9e61-63f37cd68f0a.jpg)

**Comment by dariomws** [comment]
The steps in the article worked for me. Please open or continue working with support as it's the correct way to get assistance on this issue.

Thanks.

**Comment by dariomws** [comment]
I have followed the instructions in the article in two different tenants and it works for me.

This issue was reported before:
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1326

And the screenshot was updated:
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/1386

There you can find another way to get the library ID.

@kaarins could you kindly add something else here? Thanks!

**Comment by andocromn** [comment]
Hi @dariomws, just to clarify I am not requesting support for this matter, I had the library ID and group policy working before submitting this report.  I am merely trying to help report the inaccuracy in the article so that it may be corrected.  I understand that #1386 describes other means of obtaining the Library ID, but the article in question does not provide the instructions in #1386

For the record I have attempted this in 5 major browsers and I have at least 2 tenants that do not have the "Copy Library ID" I can check more if it will prove the point but its really redundant.  #1326 seems to further indicate that extends beyond just the 2 tenants I recently setup

**Comment by scanum** [comment]
@andocromn Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Pentao** [comment]
I can confirm that the "Copy library ID" option appears. But only if you are using an administrator account.

**Comment by jeopardize95** [comment]
I can confirm it still does not appear, admin or not. Seems to be tenant specific.

**Comment by andocromn** [comment]
Hi @Pentao I have been testing licensed account with global admin permissions.  None of my tenants have the Copy Library ID option.  I suspect it may have to do with the time period in which the tenant or sharepoint site was created

**Comment by dariomws** [comment]
@kaarins could you kindly help? There are people who are still experiencing this issue. Thanks!

**Comment by andocromn** [comment]
I don't pretend to be an expert on SharePoint, but from my experience the site is created from a template... And this would be part of the template, right? So if it was removed from them template, these changes wouldn't apply to pre-existing sites created from the template, only sites created after this change was made to the template

**Comment by scanum** [comment]
@kaarins could you kindly help? There are people who are still experiencing this issue. Thanks!

**Comment by scanum** [comment]
@kaarins could you kindly help? There are people who are still experiencing this issue. Thanks!

**Comment by kaarins** [comment]
@andocromn and any others, if you are still experiencing this issue, please contact Support because the team would like to investigate. We don't want to add the PowerShell instructions to this article because the feature should work as described. We will need you to collect and provide a Fiddler trace. When you contact support, please include a link to this issue. Thank you.
