### ISSUE TITLE
SPMT File Size Limit

### ISSUE THREAD

**Issue by harp365** [MicrosoftDocs/OfficeDocs-SharePoint#2348]
I quite frequently get the following failure message when using SPMT:

Scan File   Failure:File size exceeds limit
--

Please could this be at least added and spelt of that the limit seems to still track the 15GB SharePoint limit and not the 100GB. Ideally as part of this someone could make it align with the browser upload limit, but if not it might also be worth specifying the workaround for this if a file exceeds 15GB. The workaround is to manually upload the file which is not ideal when trying to script this process end to end.

Thanks

Henry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfa08336-690e-0d21-6491-3f14f6d13391
* Version Independent ID: 8927975a-7956-fc72-055e-36603e4eddaf
* Content: [Troubleshoot SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/troubleshooting-common-spmt-issues)
* Content Source: [migration/troubleshooting-common-spmt-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/troubleshooting-common-spmt-issues.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@harp365  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @harp365 

Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by harp365** [comment]
Hi, not sure what has been done here. Maybe I cannot see for looking but the documentation is the same and the issue still remains. Not sure what has happened for this to be closed?

Thanks

**Comment by litex1982** [comment]
@harp365 Do you managed to have a solution for this? we had the same problem here
