### ISSUE TITLE
Can you provide more details for the advanced settings Filter Subsites

### ISSUE THREAD

**Issue by spg-iwilson** [MicrosoftDocs/OfficeDocs-SharePoint#2438]
The Filters section of the migration settings includes a property for Filter Subsites. Can you provide more details such as:
* should this be the absolute or relative
* does this automatically exclude all child sites?
* how to separate multiple urls? Commas, semicolons?
* should spaces and other special characters be url encoded?
* is there a maximum length for this property

Similar feedback for the Filter lists and libraries and Filter content types. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dad86450-d9ac-4cc4-fc75-63f8b285c298
* Version Independent ID: d1e8c85a-b365-78c0-be1a-5a03ee082491
* Content: [Available settings in SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/spmt-settings)
* Content Source: [migration/SPMT-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/SPMT-settings.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@spg-iwilson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@spg-iwilson thank you for reaching out. Please have another look at the article, I see it was updated a few days ago after your initial comment. Please let me know if you need further assistance.

**Comment by spg-iwilson** [comment]
The only information for Filter Subsites is the text "Enter any subsite names you want to exclude from migration". This doesn't cover any of points I raised in my comments

**Comment by scanum** [comment]
@spg-iwilson  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by hctitsobs** [comment]
@scanum Can this be re-opened? The documentation I'm seeing (https://learn.microsoft.com/en-us/sharepointmigration/spmt-settings) still doesn't provide any of the details that @spg-iwilson asked for. Thanks.
