### ISSUE TITLE
"Configure team site libraries to sync automatically"

### ISSUE THREAD

**Issue by cschafft** [MicrosoftDocs/OfficeDocs-SharePoint#323]
More options in the GPO seems available, like "Configure team site libraries to sync automatically". It would be useful to get an example to illustrate expected "Value name" and "value". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by CBeckstrand** [comment]
Yes, it appears the GPO option listed is not working correctly. Can we please get more documentation and/or an ETA on when this will be functional?

**Comment by kaarins** [comment]
Thanks for this feedback! I'm investigating and will get back with you shortly.

**Comment by kaarins** [comment]
@cschafft @CBeckstrand, the article now includes info on this GPO! Thank you again!

**Comment by cschafft** [comment]
Many thanks for the update!
One last question: the libraryID is the full string obtained after the click on "Copy Library ID" and this exact string must be copied in the GPO? Is there a step needed to rewrite the character set (e.g. replace %2D by "-")?

**Comment by kaarins** [comment]
@cschafft and @CBeckstrand , I just removed the content about this setting. It is in the .adml and .admx files, but not turned. (The team is making some changes.) It will be available shortly. When it is available, you'll be able to paste the string exactly as it's copied to the clipboard.

**Comment by Mark7even** [comment]
Any update on when this feature will be released?

**Comment by win2000b** [comment]
According to the update release notes this feature is now available in build 18.212.1021.0008

https://support.office.com/en-us/article/new-onedrive-sync-client-release-notes-845dcf18-f921-435e-bf28-4e24b95e5fc0

I updated to this build and have tried configuring with the library ID copied and pasted into value but it doesn't work for me. Do we need to change the formatting or simply a copy and paste

**Comment by MayTakeUpTo8Hours** [comment]
We're experiencing the exact same issue.

Client Version is 18.212.1021.008.
.adml and .admx files are the newest available.
The registry Value was set correctly at "HKCU\SOFTWARE\Policies\Microsoft\OneDrive".
The library ID was copied unmodified from a Sharepoint Online library.

After 2 days of waiting the Client still doesn't have the location of the team site attached.

**Comment by grustni** [comment]
I have applied the following setting for One Drive GPO:
- Configure team site libraries to sync automatically
-- Configured with two Library IDs.
-- Confirmed that the registry is present on my computer
-- No libraries are mapped after a reboot
-- My personal OneDrive folders are mapped

- Enable OneDriev Files on-demamd
-- the settings works for personal onedrive for business folders/files

- Silently configure OneDrive using the primary Windows Account
-- Did not log me in automatically.

**Comment by kaarins** [comment]
@IoTJonL , can you take a look at this? Thanks!

**Comment by comunicFR** [comment]
Hi all,
i am very interessted in this GPO, to configure automatically sharepoint sites on onedrive client...
Tried with site ID, with or without the {}, but site never come up...
Some updates on this ?

**Comment by motaba1** [comment]
It was working for me with support from Microsoft.
In GPO there has to be whole value from "Copy library ID" (tenantId=xxx&siteId=xxx&webId=xxx&listId=xxx&webUrl=httpsxxx&version=1). 
Windows 10 or Office has to be registered to Insiders ring. This was my problem. 
Then you need to wait some time (next day) and sync is here.
Libraries from Communinacions site are synchronised too.

**Comment by comunicFR** [comment]
wow thank you !
how can you grab this famous ID link ?
ans secondly, i can't put all my clients tenant members of the insides ring .. will wait for the production release... do you have an eta from Microsoft ?

**Comment by motaba1** [comment]
articke says: 
To find the library ID, sign in as a global or SharePoint admin in Office 365, browse to the library, and click the Sync button. In the "Starting sync" dialog box, click the Copy library ID link.
It will be long string like tenantId=xxx&siteId=xxx&webId=xxx&listId=xxx&webUrl=httpsxxx&version=1

**Comment by cschafft** [comment]
Is there an eta for the production release? I'm in the same situation as comunicFR.

**Comment by rbnmk** [comment]
I am also looking for the ETA for this release. Alot of customers could benefit from this (if its working as expected ;-))

**Comment by CoertK** [comment]
I found this feature on the 365 roadmap. Release scheduled for this month. https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=27031

**Comment by schenardie** [comment]
As stated before the feature is still on Insider Preview. I did a test with the same keys on an Insider Preview and a Current Branch and the current branch doesnt work. That is probably because it does not have the latest OneDrive Version. Current Branch is 19.012.0121.0009 and Insider Preview 19.022.0203.0005. 

I got another request though. 
When i edit the regkey [HKCU\Software\Policies\Microsoft\OneDrive\TenantAutoMount]"LibraryName"="LibraryID" manually i can get everything to work on the insider preview no problems. But if i try to deploy this key via Intune with ADMX policy (refer to https://tech.nicolonsky.ch/onedrive-known-folder-move-ms-intune/) a problem happens because it seems XML parser on Intune cannot interpret URL encoding.

For this example i'll be only getting the tenantid part of the string to make it shorter, and also im clearly masking my tenantid.
tenantId=12345678%2D1234%2D12ab%2D195d%2D123456789&
when i try to send these config via Intune Custom CSP i can see on the event viewer logs that the parser replaces the string %2D (which is the URL encoder for dash "-") for the admx name (OneDriveNGSC~Policy~OneDriveNGSC) then it breaks the code and it fails to create the registry key. 

Can the Decode URL be used for this setting?
Example of the url decoded would be something like this
tenantId=00000111-1111-1111-2222-6cebfdc43aeb&siteId={xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx}&webId={xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}&listId={xxxxxxxx-3xxx-4xxx-9xxx-xxxxxxxxxxxx}&webUrl=https://domain.sharepoint.com&version=1

Thanks

**Comment by schenardie** [comment]
Just to complement, the decoded URL can be used. Just tested and both work.

**Comment by CoertK** [comment]
> Just to complement, the decoded URL can be used. Just tested and both work.

Thanks!

Which version of Windows 10 are you on? I have configured the policy manually in the registry as well through gpedit.msc, with both encoded and decoded URLs but it's not working yet. I am on OneDrive 19.022.0203.0005 and Windows 10 1809 17763.316.

Also can you show an example of OMA URI you used and the string?

**Comment by schenardie** [comment]
Its stated up there on the blue box

 Important
This feature is currently enabled in the Insiders ring only. To try it, join the Windows Insider program or the Office Insider program.

I turned on test device into insider preview (and it installed 18346.1 - 1903) not sure it does work only with the latest version of OneDrive.

for the URI after you imported the ADMX you should use ./User/Vendor/MSFT/Policy/Config/OneDriveNGSC~Policy~OneDriveNGSC/AutoMountTeamSites

**Comment by CoertK** [comment]
> Its stated up there on the blue box

It says Office Insider or Windows Insider. So I assume it works with any of the two, but it looks like it only works if you have both.

The string should look like this?
<Enabled/><Data id="AutoMountTeamSitesListBox" value="Test&#xF000;tenantId=00000111-1111-1111-2222-6cebfdc43aeb&siteId={xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx}&webId={xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}&listId={xxxxxxxx-3xxx-4xxx-9xxx-xxxxxxxxxxxx}&webUrl=https://domain.sharepoint.com&version=1"/>

**Comment by schenardie** [comment]
On mine it was working with only windows insider but im doing some more testing now and it doest seem to work anymore. Weird. The string is almost right i used codebox.net to translate the ampersend and it ends up being like &amp instead of only &. The same way you need the decode #xf0000

**Comment by EliWallic** [comment]
Is there now any date when it might be GA? would be really nice to have it via GPO...currently i wrote my own script to automatically start or stop a sync for an SPO document library for the endusers.

**Comment by andyturn31** [comment]
Still not working on latest Windows (version 1809 Build 17763.379).  As previous comment, when will this feature be GA?

**Comment by skilmartin** [comment]
Any word on this yet?  I'd very much like to sync document libraries automatically with OneDrive and Intune.

**Comment by EliWallic** [comment]
I finished my script which is doing the same like the GPO (Naming/Start/Stop/cleanup I addition). Not really hard but annoying that this feature is not ready yet. I don't know where the problem is. Maybe Microsoft can post a hint that other people can help?! It is still on GitHub......

**Comment by CoertK** [comment]
Care to share your script with us? This GitHub is only for the content of the docs page, not the actual feature.

**Comment by schenardie** [comment]
Name: AutoMountTeamSites
OMA-URI: ./User/Vendor/MSFT/Policy/Config/OneDriveNGSC~Policy~OneDriveNGSC/AutoMountTeamSites
Data type: String
Value (exactly how it is below replacing the x's for the values copied on the ID and the weburl replaced with yours:
<enabled/>
<data id="AutoMountTeamSitesListBox" value="MydocstenantId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&amp;siteId={xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}&amp;webId={xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}&amp;listId={xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}&amp;webUrl=https://yourdomain.sharepoint.com/sites/company&amp;version=1"/>


*note that between the value name (Mydocs) and the actual value (tenantid=....) there is an encoded delimiter (0xF000)


That worked for me (given the admx is imported and the other policies for silentautoconfig are also deployed)

**Comment by schenardie** [comment]
enabled
data id="AutoMountTeamSitesListBox" value="MydocstenantId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&amp;siteId={xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}&amp;webId={xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}&amp;listId={xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}&amp;webUrl=https://yourdomain.sharepoint.com/sites/company&amp;version=1"

had to remove the <> and / 


*note that between the value name (Mydocs) and the actual value (tenantid=....) there is an encoded delimiter (0xF000)

**Comment by skilmartin** [comment]
Hey schenardie...I've been trying to get this to work the way you indicated, but I've been unsuccessful.  I've tried on 1809 and 1903 without any luck.  Here are my exact values based off of your recommendation:

OMA-URI: ./User/Vendor/MSFT/Policy/Config/OneDriveNGSC/AutoMountTeamSites
Value:
enabled
data id="AutoMountTeamSitesListBox" value="SalestenantId=xxxxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxxxxxxxxxx&siteId={xxxxxxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxxxxxxxxxx-xx}&webId={xxxxxxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxxxxxxxxxx-xx}&listId={xxxxxxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxxxxxxxxxx-xx}&webUrl=https://mydomain.sharepoint.com;version=1"

Do you see anything that looks out of whack?

**Comment by scanum** [comment]
@IoTJonL Hi! Any updates on this? Thanks!

**Comment by skilmartin** [comment]
I'd love an update as well!! =)

**Comment by tommrihu** [comment]
Any news?

**Comment by amore514** [comment]
Any news? I would love to start using this. Not willing to move my user's computers to the insider ring.

**Comment by skilmartin** [comment]
I got it to work via PowerShell but only on 1903.  Luckily 1903 is scheduled to be released early this month.

**Comment by amore514** [comment]
Can you please post your PS script?

**Comment by skilmartin** [comment]
$tenantAutoMountRegKey="HKLM:\SOFTWARE\Policies\Microsoft\OneDrive\TenantAutoMount"

$autoMountTeamSitesList= @{
    
    #Enter your SharePoint libraries to configure here as key/value pairs.  Library names can be anything.
    SalesLibrary="SharePointLibraryIDGoesHereInsideQutoes"
    AccountingLibrary="SharePointLibraryIDGoesHereInsideQutoes"
    HRLibrary="SharePointLibraryIDGoesHereInsideQutoes"

}


if (-not (Test-Path $tenantAutoMountRegKey)){
    
    New-Item -Path $tenantAutoMountRegKey -Force

}


#add registry entries from the hashtable above
$autoMountTeamSitesList.GetEnumerator() | ForEach-Object {
        
    Set-ItemProperty -Path $tenantAutoMountRegKey -Name $PSItem.Key -Value $PSItem.Value -ErrorAction Stop




A few things to note - It takes some time for the libraries to show up.  Sometimes they showed in 5 minutes sometimes it takes hours.  Not sure why.  Also, if the user doesn't have permission to a SharePoint site that you mount, it will still show up on the sidebar, but will be blank.  For more info, I referenced this site: https://tech.nicolonsky.ch/onedrive-automountteamsites/

**Comment by amore514** [comment]
First off thank you for taking the time to make this! Question about your script and the direction on your site. 
Getting the SharePoint library ID results in a long URL for me but in your image, it shows "tenantid=7955e"

This is the ID I am getting when I click Copy library ID
https://xxxxxxxxx.sharepoint.com/:p:/r/sites/developmentteam/Shared%20Documents/5-6-2019%20Development%20Committee,%20V3.pptx?d=a7a1e971bdf264c4e8235663031b18f02&csf=1&e=YqkQJl

Do I use the whole thing or just some part of it?

**Comment by skilmartin** [comment]
That is not the library ID.  That is just the URL to access the library.  To attain the library ID, click the "Sync" button and choose Copy Library ID.

![image](https://user-images.githubusercontent.com/49403304/57157578-175a2980-6daf-11e9-97f1-7fff02823cac.png)

**Comment by amore514** [comment]
Ya I saw that, when I click Copy library ID this is what I get

https://xxxxxxxxx.sharepoint.com/:p:/r/sites/developmentteam/Shared%20Documents/5-6-2019%20Development%20Committee,%20V3.pptx?d=a7a1e971bdf264c4e8235663031b18f02&csf=1&e=YqkQJl

what am I missing?

**Comment by amore514** [comment]
Scratch that, I opened it in Edge and got a different result. 

tenantId=f9bab3cd%2D5d14%2D4378%2Dg3e6%2D334566bdad5d&siteId=faf2fb86%2Db34a%2D4259%2Db754%2Dd5976fe1c34c&webId=5ad47a32%2D9a29%2D4542%2D96cc%2Dcb84c7254e3c&listId=%7B93B4D41D%2DF57E%2D4BA5%2DAE7D%2D497EF5D6F124%7D&webUrl=https%3A%2F%2Fxxxxxxxxxxxx%2Esharepoint%2Ecom%2Fsites%2Fdevelopmentteam&version=1

Its HUGE do i use the whole thing?

**Comment by amore514** [comment]
Also is a restart required?

**Comment by skilmartin** [comment]
Yes, you should use the whole thing.  That is why its not working via ADMX ingestion.  Its too long of a value and gets truncated when written into the registry.  Hopefully Microsoft will fix this.

Honestly, I'm not sure if a restart is required.  I forced a sync with Intune and rebooted anyway.  If I had to guess, I'd say a restart is probably required for the script to run under the computer context.  Also, you can always check the registry at "HKLM:\SOFTWARE\Policies\Microsoft\OneDrive\TenantAutoMount" to see if the keys for each library were created successfully by the script.

**Comment by amore514** [comment]
I can confirm the reg key is being created. Thank you! I'll give it some time, praying this works.

**Comment by skilmartin** [comment]
And just to be clear, make sure you're using 1903 or it def won't work.

**Comment by tonyfairbanks** [comment]
For what it's worth I have this working fine, on 1809, via GPO. Once I set the update ring to Insiders via GPO and waited a few hours my libraries showed up. It even works on the 1607 LTSB machines I have. 
![Capture](https://user-images.githubusercontent.com/6955271/57162342-8e91bc80-6db3-11e9-8e0e-f07c25def9d1.PNG)
![Capture2](https://user-images.githubusercontent.com/6955271/57162343-93567080-6db3-11e9-9ea9-ccc1a4970a09.PNG)

**Comment by skilmartin** [comment]
Yeah, its different for Intune.  Intune doesn't use the old school GPO engine.  It uses something called Policy Configuration Service Provider.  So I think Policy CSP needs to support the AutoMount settings, which were only just added in 1903.

**Comment by tseward** [comment]
You can load the OneDrive.asmx into InTune (https://docs.microsoft.com/en-us/windows/client-management/mdm/enable-admx-backed-policies-in-mdm) if needed.

**Comment by skilmartin** [comment]
Yeah, but it doesn't work for the AutoMountTeamSite policy.  It truncates the Library ID when it adds it to the registry, and then fails to automount.  That's why we're using PowerShell here.

**Comment by amore514** [comment]
I think I like the PS script better than Group Policy. With a PS script using intune, I can get very granular on who is getting the mapping ver GP is done at an OU level.

**Comment by EliWallic** [comment]
My solution for doing the same like GPO but without putting the complete company into an insider ring: https://github.com/EliWallic/PowerShell/blob/master/Automate-OneDriveSync.ps1
Not a perfect one but dynamic enough to do its job.

Please finalize this feature in GPO for the production rings!

**Comment by EliWallic** [comment]
> Care to share your script with us? This GitHub is only for the content of the docs page, not the actual feature.

https://github.com/EliWallic/PowerShell/blob/master/Automate-OneDriveSync.ps1

**Comment by amore514** [comment]
I'm not sure the insider ring still applies, from my testing as long as you have the latest one drive client it works.

**Comment by chrios** [comment]
Tested with OneDrive Version 2019 (19.070.0410.0005), Windows 10 Pro Version 1809 (OS Build 17763.475) and added both HKLM and HKCU keys. Neither work after a reboot. Still have to sync the site manually :(

**Comment by CoertK** [comment]
I have been trying this for 6 months, never got it working. Maybe it's not enabled for some data locations. I am only using Europe SharePoint sites.

**Comment by jedimaster4007** [comment]
I finally managed to get the computer policy to work. I'll try to provide as much detail as I can so that others can get this working as well.

I'm not sure if it is required, but I found a website via Google which allowed me to decode the SharePoint library IDs (Google search "decode url" and it should be the first result), and I also put the actual site URL (near the end of the ID) in quotes. I am running Windows 10 1803, Office 365 Monthly Channel, OneDrive version 19.070.0410.0005 (Insider preview checkbox selected in OneDrive settings). I am not on the Windows Insider ring, nor the Office Insider ring, but I did check the box for "Insider preview updates" in the About tab in OneDrive settings. That checkbox is what finally allowed the libraries to start syncing. THAT SAID, it still took a day or so before they started syncing, and from what I've read online, that is by design. So, unfortunately, you probably won't be able to see any instant results while trying to get this working, since it can take 8 hours or more before the libraries will show up. I'm not sure if the Office monthly channel is required, it's just that all of our IT machines are on the monthly channel and we haven't tested the semi-annual channel yet.

**Comment by scanum** [comment]
@cschafft @jedimaster4007 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by CoertK** [comment]
This is not resolved. The suggested solutions are no guarantee for it to work. Is there any MS tech that can provide more info?

**Comment by tommrihu** [comment]
I Agree!!!!!! with CoertK

**Comment by CBeckstrand** [comment]
Yes, this is still not working at all for me as well. We need this reopened until this is reliable.

I am running and brand new Win10 Pro 1903 install that I can't get this working on no matter what I do. I have verified all the GP settings are correct and I can see the registry key getting created but nothing is ever mapped in OneDrive. I have the insider ring box checked in OneDrive and I'm on the latest build. We really need this working for new client migrations to Sharepoint.

**Comment by CBeckstrand** [comment]
I have also tried both the computer and user GPO settings. I verify registry keys are created in the correct hive (HKLM or HKCU) but nothing is mapped in OneDrive no matter how long I wait.

**Comment by jflieben** [comment]
I would strongly suggest not just using HKLM but also HKCU for the automount setting, i doubt every user is a member of every team in most setups ;)

**Comment by yatesa** [comment]
GPO appears to work but solution is pretty useless for us. Waiting 8 hours is not workable for us. I was at least hoping that the Value name would also define the name that appears when it syncs, but it defaults to "Site Name - Documents" which is annoying and can be too long.
We are still having to a custom Powershell script to auto sync team site libraries, which 1) allows the sync to occur immediately 2) We can define any name we want. However, its still not the perfect solution for us either because we rely on third party dll to check onedrive status and its less reliable in returning correct status since Files On Demand was added.
So Microsoft please provide GPO that maps immediately and allows you to set custom name OR update OneDrive with decent API access so we can map ourselves!

**Comment by skilmartin** [comment]
I just read yesterday in a blog post (I'll see if I can find and post later) that the 8 hour delay isn't actually a delay.  It can start syncing any time within the 8 hours.  The concept being that not all the computers start syncing at once and destroying the bandwidth.

**Comment by speers-cbx** [comment]
As you can see from all of the comments and duplicate bug reports for this feature set (Configure team site libraries to sync automatically”) this is a very much needed feature and functionality:
It sounds like its hit or miss. Some are getting this to work but many are not.
I found that some libraries will offer the “copy id” link but not all.
Which version of Windows 10 does this work in? It says insiders, are we talking a Windows 10 Insider builds or the one drive software itself?
When you copy the id, there’s been a lot of questions if its formatted correctly or does it have to be rewritten?
Does this only work for MS Teams based SharePoint libraries or any SP library?
Assuming group policy is working correctly, you should see it apply some registry keys which can be verified. Once that takes place, and you are signed into OneDrive and have on demand sync enabled you should see the libraries populate correct?

**Comment by IdabelleDibble** [comment]
Was working beautifully until MS decided to stop putting the " Copy Library ID" when clicking on sync. Is there another way to get Library ID?

**Comment by jflieben** [comment]
> Was working beautifully until MS decided to stop putting the " Copy Library ID" when clicking on sync. Is there another way to get Library ID?

It still works in Internet Explorer, all other browsers I tried are broken, I'm using an alternative method (PowerShell) to auto-add libraries to O4B until this feature is production ready: https://www.lieben.nu/liebensraum/2019/06/ultimate-folder-redirection-for-onedrive-teams-and-sharepoint/

**Comment by richardjgreen** [comment]
> > Was working beautifully until MS decided to stop putting the " Copy Library ID" when clicking on sync. Is there another way to get Library ID?
> 
> It still works in Internet Explorer, all other browsers I tried are broken, I'm using an alternative method (PowerShell) to auto-add libraries to O4B until this feature is production ready: https://www.lieben.nu/liebensraum/2019/06/ultimate-folder-redirection-for-onedrive-teams-and-sharepoint/

I have tried with IE, Edge (Standard), Edge (Beta), and Chrome this morning. None of them offer me the Copy Library ID link.

**Comment by CoertK** [comment]
> I have tried with IE, Edge (Standard), Edge (Beta), and Chrome this morning. None of them offer me the Copy Library ID link.

In IE it will show the odopen protocol url, which is different from the url you could copy before. But it contains the list ID, so you can compare both string and replace the IDs to make it work.

**Comment by richardjgreen** [comment]
> > I have tried with IE, Edge (Standard), Edge (Beta), and Chrome this morning. None of them offer me the Copy Library ID link.
> 
> In IE it will show the odopen protocol url, which is different from the url you could copy before. But it contains the list ID, so you can compare both string and replace the IDs to make it work.

That's what I'm trying now. It doesn't include the Tenant ID in that string though so it's taking a little bit of craft to put it together encoded properly.

**Comment by tseward** [comment]
Hi folks, the library ID issue is under discussion at https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1326 (note this should be reopened soon). There are some alternative methods linked within that Issue to get the necessary IDs for automount.

**Comment by IdabelleDibble** [comment]
Thank you all for comments. tseward this discussion will help immensely!

**Comment by falccc** [comment]
For those that can't see the copy library ID link, ensure you have signed into sharepoint with an account that is a Global Admin or SharePoint Admin.  If you don't the link won't show.

Having said that we cannot get this to work.  Windows 10 1809, Onedrive Build 19.152.0927.0012.  The group policy does apply (the key is in the registry).  We converted the link using powershell to take care of the Escaped characters as per [https://docs.microsoft.com/en-us/onedrive/use-group-policy#AutoMountTeamSites](url)

For those that have it working, does the Library name appear in File explorer but then take hours before files/folders within the it to appear?  Or does it take hours before the Library name shows in File Explorer?

**Comment by skilmartin** [comment]
@falccc - Two things:

1) It takes hours before the library name even shows in File Explorer.  But once it shows, they will start populating immediately.
2) It seems that if you click Sync button on the SharePoint Document Library, once it opens in OneDrive, the splash screen from SharePoint will change to say "We are connecting to OneDrive on your device.  Copy Library ID to configure this library to sync automatically."  But to be clear, that is not what the splash screen says when you click Sync.  It only changes once the library has been opened in OneDrive to sync.  (I know that sounds stupid and confusing so let me know if I can clarify).

**Comment by falccc** [comment]
@skilmartin 

Thanks for confirming point 1.  Try as we might, we cannot get this to work.  To make matters even more confusing, the gui options in Onedrive settings are different on 2 different computers.  These computers are both VM's built with the same process, logged on with the same user accounts, same group policies etc applied, and same version of the Onedrive client!

**Comment by jitterbox** [comment]
This issue must be reopened. The GPO library syncing feature has _still_ not been released to production, and even with our entire company on the latest Insider Build - for which it is _supposed_ to be enabled - the feature is still not working.  We've spent over two weeks being stalled by support, only to find that despite being documented (and **not** as preview or pre-release) for a full year, the GPO-based syncing is still not working or available.  If the documentation is not the authoritative source of a product's functionality, what is?  And don't say release notes, when all they ever post is the useless statement "Bug fixes and performance improvements".

**Comment by yatesa** [comment]
We have been using GPO library sync for at least 2 months, never been on insiders build, our onedrive build is 19.174.0902.0013. Only odd thing I noticed in the docs was that it says "The special characters in this copied string are in Unicode and need to be converted to ASCII according to the following table".
Our GPO has always had unicode version with all the % entries and it has worked fine for us. Never needed or tried to convert.
I also just double checked that the sync splash screen with the "Copy library ID" link still produces the correct/same string and it still matches what we have in our GPO.

The only thing that still bugs me is that OneDrive does not immediately add the sync library, some times find you have to wait day for it to pop which obviously doesn't help those diagnosing issues as you don't know if timing thing or just not working and have to wait at least a day or two to be sure.

**Comment by gki1911** [comment]
Yes, I agree with yatesa, its a very handy feature but in testing it takes way to long to show up. It took a couple days for it to work when we could have setup the sync manually in a few minutes. I would rather have the option to have it sync immediately and use the Max Download and Upload limits and the Use OneDrive Files On-Demand settings to keep from overwhelming the network.

**Comment by PatrickF11** [comment]
Just one more comment:
For me this isn't working as well.
What I've tested:

Sending the configuration via Intune administrative template. (Once with unconverted id, once with converted library id is told by MS)

Both values appeared correctly inside the registry (HKCU\Software\Policies\Microsoft\OneDrive\TenantAutoMount) but even after two days there is no automatic library sync. (Neither one nor the other)

**Comment by jdvuyk** [comment]
So, like everyone else here.  This is a pretty important feature for anyone looking to move away from file servers to SharePoint based team drives.  Its not realistic to have new users add document libraries manually, so automation is the key.  Like most, i have the policy working (via intune) and can see the registry items.  but the libraries never show up in OneDrive.  This feature is half-baked and MS really need to pull-finger and get it sorted out.  its  pretty basic requirement and is clearly broken.

**Comment by jdvuyk** [comment]
Worth more persevering I found that this functionality actually works.  but it takes DAYS and DAYS to take effect.  I believe the best way to trigger the functionality is to wait for a day, reboot then wait for a day.  randomly things seem to appear after that.  Still shockingly terrible?  Yup.  but working? sort of.

**Comment by gherbstman** [comment]
It would be also nice to just have a "sync all users libraries" option that just syncs ALL the SharePoint libraries the user has permissions to.

The Android app already does this.

**Comment by ilhancelik** [comment]
I ran it with the steps below.

1. I made the onedrive settings with GPO. (Computer configuration)
2. I have used UNICODE and never changed.
3. In DC, users must be a one-time local admin.

In addition regedit settings (Example);

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\OneDrive]
"FilesOnDemandEnabled"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\OneDrive\TenantAutoMount]
"TEST"="tenantId=e62d7477%2Dcbc5%234235D4a12312349%2Da59d%2Db85071632067&siteId=%7B0b34534563162d45%7Bf130e934%2D7d89%2345345D4ea7%2Db07b%2Dee607a022cc1%7D&listId=%7B3647053D%2DA189%2D4B57%2DAA0C%2D91A089EAEEE9%7D&webUrl=https%3A%2F%2Fyourcom%2Esharepoint%2Ecom&version=1"

**Comment by nikmanzotti** [comment]
> Only odd thing I noticed in the docs was that it says "The special characters in this copied string are in Unicode and need to be converted to ASCII according to the following table".
> Our GPO has always had unicode version with all the % entries and it has worked fine for us. Never needed or tried to convert.

Same here! I've successfully created a working GPO without converting Unicode to ASCII. As this issue is closed, quite dated and focused on a different matter, I will open a new one just for the ASCII/Unicode issue. I'll edit this comment as I have an issue number to link!

**Comment by joeldeteves** [comment]
> Just one more comment: For me this isn't working as well. What I've tested:
> 
> Sending the configuration via Intune administrative template. (Once with unconverted id, once with converted library id is told by MS)
> 
> Both values appeared correctly inside the registry (HKCU\Software\Policies\Microsoft\OneDrive\TenantAutoMount) but even after two days there is no automatic library sync. (Neither one nor the other)

Hello, I realize this is an old thread but just went through a saga with Microsoft Support and I don't see the answer here, so I'm adding it. In order to resolve the problem other users have mentioned in this thread, we had to follow a couple of additional steps not documented in the GPO settings:

1) The instructions on the Microsoft Docs for this policy state that **"The special characters in this copied string are in Unicode and must be converted to ASCII"** see https://docs.microsoft.com/en-us/onedrive/use-group-policy#configure-team-site-libraries-to-sync-automatically for more info.

    The easiest way to do this is to paste the string between the quotes in the following PowerShell command:

    `[uri]::UnescapeDataString("Copied String")`

    This will output the string in the proper format, e.g:

    tenantId=02ad5f9c-3696-477b-8cb3-9ba4e0a9ac9c&siteId={87a9f4b2-757b-4663-b19e-d58398f0f1e4}&webId={d1135130-a5e3-41d2-a8f1-a547508eaf04}&listId={265BA069-9F1C-4065-83AC-B7C7A0CE4C28}&webUrl=**https://contoso.sharepoint.com&version=1**

2) In addition, the policy was still not working for us in spite of following these instructions. After putting in a support case with Microsoft, we were informed that in order to resolve the problem we needed to add a trailing slash to the **webURL** portion of the string, immediately after the `.com` but before the `&version=1`:

    tenantId=02ad5f9c-3696-477b-8cb3-9ba4e0a9ac9c&siteId={87a9f4b2-757b-4663-b19e-d58398f0f1e4}&webId={d1135130-a5e3-41d2-a8f1-a547508eaf04}&listId={265BA069-9F1C-4065-83AC-B7C7A0CE4C28}&webUrl=**https://contoso.sharepoint.com/&version=1**

    Note the addition of the trailing slash in the second example.

Personally, I think this is really silly and I hope Microsoft addresses it!

**Comment by jitterbox** [comment]
Thanks, @joeldeteves, we gave up after going through a multi-month slog with MS support (which they all seem to be, these days), and this is probably why it has never worked for us... I for one will be trying out your suggestions, much appreciated.

**Comment by HansBrender** [comment]
Microsoft should not change the code. The first time I have [described ](https://hansbrender.com/2019/03/27/onedrive-gpo-configure-team-site-libraries-to-sync-automatically/)it, **I do not have use convert to ascii,** and **I do not have add a "/" after .com** and it **works**. 

But then Microsoft decides, to switch this GPO from "Computer Configuration" to "User configuration"

The last time I have checked was Juli 2020.
I will check again, without ASCII convert But with the "/" and one without

**Comment by HansBrender** [comment]
For the test I have chosen 4 differnt sites:
Test 1: **without** ASCII Konvertierung - **without** "/" : Successful
Test 2: **without** ASCII Konvertierung - **with** "/" : Successful
Test 3: **with** ASCII Konvertierung - **without**  "/" : Successful
Test 4:  **with** ACII Konvertierung - **with** "/": Successful

Now that all possibilities have been successfully completed, I can only see possible sources of error:
- The GPO "Files on Demand" was not established 
- You have more than 5000 Folder/files in the document library
- You have more than 1000 devices  for the GPO 

_Test-Environment:_ 
Windows 11 Build 22494 ,  Windows 10
OneDrive Version Insider 21.220.1024.0001 
Group Policy  rolled out via Local Group Policy Editor  (4 entries in the Registry)

means: The [description ](https://docs.microsoft.com/en-us/onedrive/use-group-policy#configure-team-site-libraries-to-sync-automatically)is correct. 

**My question is, why do we have to convert it to ASCII?**  
@gacarini @joeldeteves @Jitterbox

**Comment by joeldeteves** [comment]
> For the test I have chosen 4 differnt sites: Test 1: **without** ASCII Konvertierung - **without** "/" : Successful Test 2: **without** ASCII Konvertierung - **with** "/" : Successful Test 3: **with** ASCII Konvertierung - **without** "/" : Successful Test 4: **with** ACII Konvertierung - **with** "/": Successful
> 
> Now that all possibilities have been successfully completed, I can only see possible sources of error:
> 
> * The GPO "Files on Demand" was not established
> * You have more than 5000 Folder/files in the document library
> * You have more than 1000 devices  for the GPO
> 
> _Test-Environment:_ Windows 11 Build 22494 , Windows 10 OneDrive Version Insider 21.220.1024.0001 Group Policy rolled out via Local Group Policy Editor (4 entries in the Registry)
> 
> means: The [description ](https://docs.microsoft.com/en-us/onedrive/use-group-policy#configure-team-site-libraries-to-sync-automatically)is correct.
> 
> **My question is, why do we have to convert it to ASCII?** @gacarini @joeldeteves @jitterbox

No idea how your environment differs but none of this is correct for ours.

The only way we could get it to work was by adding the "/" to the end of the WebURL.

This is documented in our case ID with Microsoft.

**Comment by schenardie** [comment]
Check the sharepoint site type. Automount is not support on communications site. By default since 2019 all root sites are of the communication type.

**Comment by HansBrender** [comment]
@schenardie 
jhave tested that to. it works. And I do not have changed anything
