### ISSUE TITLE
Error on the question : Does Migration Manager transfer permissions for shared drives?

### ISSUE THREAD

**Issue by lfrancfort** [MicrosoftDocs/OfficeDocs-SharePoint#3623]
Hello, the answer to this question is "no", and it seems to be wrong : I copied a shared drive to a SPO site doclib, and all default permissions set on the doclib were superseeded by the ones applied during content migration.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9b62f24-44b9-731f-f143-6a05fa1da328
* Version Independent ID: 15452c1d-d06c-e8f5-9b87-b5fdd0f375ab
* Content: [Migration Manager Google FAQs - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/mm-faqs-google)
* Content Source: [migration/mm-faqs-google.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-faqs-google.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
https://learn.microsoft.com/en-us/sharepointmigration/mm-google-overview#google-shared-drives

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by lfrancfort** [comment]
Hello, no the issue is not resolved. The documentation is wrong : it states that permissions are not migrated, but they are.
