### ISSUE TITLE
Article does not align with "Account permissions and security settings in SP Servers"

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/OfficeDocs-SharePoint#810]
This article does not align with the naming conventions used in https://docs.microsoft.com/en-us/sharepoint/install/account-permissions-and-security-settings-in-sharepoint-server-2016. For more information about naming conventions for accounts see #319 

I will provide a PR for this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c0151f1-a178-6675-31df-19b130f4e1c2
* Version Independent ID: 10fb7e98-2870-68c5-5ad2-791beaaca583
* Content: [Plan for administrative and service accounts in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/plan-for-administrative-and-service-accounts)
* Content Source: [SharePoint/SharePointServer/security-for-sharepoint-server/plan-for-administrative-and-service-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/security-for-sharepoint-server/plan-for-administrative-and-service-accounts.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr I'll grab this one.

**Comment by andikrueger** [comment]
@tseward Somehow I feel like we should have a discussion about this article and the one mentioned in #811:

Right now we do have at least three guidance for how account are used and what kind of account you should provide. I feel the most complete article is this one: https://docs.microsoft.com/en-us/sharepoint/install/account-permissions-and-security-settings-in-sharepoint-server-2016

How can we reduce redundancy and at the same time deliver this information as easy as possible? What are your thoughts?

**Comment by tseward** [comment]
@andikrueger can you close 811/812 and just add the links here so we have one common issue to work from since these are interconnected asks?

**Comment by andikrueger** [comment]
Following an overview on several articles holding recommendations on accounts and permissions in SharePoint Server:

Article | SharePoint Version | modified| Proposed change
--- | --- | --- | --- 
|[Account permissions and security settings in SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/sharepoint/install/account-permissions-and-security-settings-in-sharepoint-server-2016) | 2016, 2019 | Dec 12, 2019 | [-] Service account recommendations (A)
[Initial deployment administrative and service accounts in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/install/initial-deployment-administrative-and-service-accounts-in-sharepoint-server)| 2013, 2016, 2019 | Jan 05, 2019 | [-] Initial deployment administrative and service accounts in SharePoint Server (B) <br/> [+] Service Account recommendations (A)
[Account permissions and security settings in SharePoint 2013](https://docs.microsoft.com/en-us/sharepoint/install/account-permissions-and-security-settings-in-sharepoint-2013)|2013 |Oct 30, 2018 |There are some sections mentioning SP 2016 even though this article focusses on 2013. <br/>It should be aligned or be replaced by the first article in this table.
[Plan for administrative and service accounts in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/plan-for-administrative-and-service-accounts)|2013, 2016, 2019|Dec 17, 2019|Should align with the first article in this table and redundancy should be reduced. <br/> Actually do not see the value of this article.




Legend:
- [-] = remove 
- [+] = add

**Comment by scanum** [comment]
@andikrueger Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by andikrueger** [comment]
@scanum This issue is not resolved yet. The articles are not aligned and we need to have a further discussion. Please reopen. See #1079 for further details.

**Comment by andikrueger** [comment]
@officedocsbot reopen
