### ISSUE TITLE
"You need to be site collection administrator"

### ISSUE THREAD

**Issue by VeroniquePalmer** [MicrosoftDocs/OfficeDocs-SharePoint#834]
I am Global Admin on the tenant and site collection administrator on the source and target site collections, but it doesn't populate any content in any of the sites I choose, as well as the top level site.  It just keeps saying "you need to be a site collection admin". Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193d7cc4-4270-f69e-262b-6384a273f835
* Version Independent ID: 6625a0f7-e4d0-2352-d78a-0a82273b1f07
* Content: [Introducing the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool#feedback)
* Content Source: [migration/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/introducing-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
Hi Veronique:  Sorry you are having issues.   At what point do you get the error that you need to be a site collection admin? When you are entering the target/destination in SPMT?

**Comment by VeroniquePalmer** [comment]
When entering the source library.

**Comment by JoanneHendrickson** [comment]
So apologies in advance, but just to be sure 
1. Launched SPMT, logging in using your Global Admin O365 credentials for your destination/target. 
2. You selected SharePoint as your source, -- and when prompted entered the path of your on-prem site collection and then your credentials for your SharePoint Server (what version?) that are permissioned as Site collection admin
3. Error.

What version of SharePoint Server are you attempting to migrate from?
3.

**Comment by VeroniquePalmer** [comment]
Oh, no I'm pointing it to SharePoint Online.  I want to move stuff from one online site to another.

**Comment by JoanneHendrickson** [comment]
Unfortunately, the SPMT tool doesn't support migrating content from one tenant to another tenant.  It's definitely high on the wish list.

**Comment by VeroniquePalmer** [comment]
I am not trying to migrate between tenants, only between site collections in one tenant.



Sent from my phone, please excuse any brevity or typos


-------- Original message --------

**Comment by NickLareau** [comment]
Hi Joanne, I'm running into the same issue. Since onedrive to onedrive is not a thing just yet, Is there anyway to download the contents of a onedrive account locally for retention/litigation hold?

**Comment by NikNak82** [comment]
I have this problem too. I'm trying to migrate each users home folders from our file server to their OneDrive accounts. I was able to do this before with the previous versions. Now I get the site collection admin error. I am a Global Admin

**Comment by scanum** [comment]
@VeroniquePalmer Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by nthoman** [comment]
I don't think this is closed. I just downloaded the public preview and I still can't move documents from one document library to another in SharePoint Online.
